### ISSUE TITLE
Crate causes GUI bug that locks all windows

### ISSUE THREAD

**Issue by Shybella** [codeHusky/HuskyCrates-Sponge#82] opened 2018-07-23 01:36 UTC
video: https://gyazo.com/b78341adb309be7b9f644f4bf867407f**
If you close the GUI before the item is rewarded that's when it glitches and causes other gui windows to be unable to access

This was originally a Sponge bug that was fixed and did work but recently it randomly happens to a player. Sponge told me to open a bug report with you.

I cannot reproduce this like before it just randomly happens. If you need more info I am able to help.

**Comment by codeHusky** [comment] 2018-07-23 01:56
Make sure your updated on both HuskyUI and HuskyCrates.
Please post your versions.

**Comment by Shybella** [comment] 2018-07-23 02:03
Yeap, on latest.
HuskyCrates-v2.0.0-PRE7-H4
HuskyUI-v0.6.0-PRE2-H2

**Comment by Shybella** [comment] 2018-11-12 02:30
Any updates on this?

**Comment by codeHusky** [comment] 2018-11-13 14:21
If you have a consistent method to reproduce this, that would be very helpful

**Comment by Shybella** [comment] 2019-02-20 13:01
Cannot find a method to reproduce. Having other server owners experiencing the same thing and they cannot find a reproduction as-well.

Finding a reproduction isn't possible. I've spent too much time trying to figure this out and totally abandoned the plugin now. 

This is caused by something wrong with Spongeforge and spans back a few months when Blood was making initial fixes in SF to fix this issue and told me to open a bug report with you.

**Comment by codeHusky** [comment] 2019-02-20 14:54
You can't just close an issue if you can't reproduce it. When I have time I'll still try a few things.

**Comment by krisjenner** [comment] 2019-02-26 22:22
Sorry if this is unwarranted but this is the bug i was experiencing and was fixed by backdating to recommended Sponge 7.1.5

**Comment by codeHusky** [comment] 2019-02-26 22:23
You should be using recommended anyway.

**Comment by Shybella** [comment] 2019-03-03 18:13
Click the key on the crate and press escape before it's finished rewarding. Do this fast, may take multiple tries.

This seems to happen only while you close the window before the item is rewarded.

**Comment by Shybella** [comment] 2019-03-03 20:19
https://www.youtube.com/watch?v=71smRSeGVWY&feature=youtu.be

**Comment by codeHusky** [comment] 2019-03-03 22:56
Thanks for the report and reproducible steps to achieve this bug. I'll be testing this and making fixes to prevent it for the next update

**Comment by codeHusky** [comment] 2019-03-04 02:50
@Shybella I have a suspicion that when this occurs you may get an error in console. Could you reproduce this issue and check for that?

**Comment by codeHusky** [comment] 2019-03-04 03:08
**Potentially resolved in v2.0.0-PRE9H2**

**Comment by Shybella** [comment] 2019-03-04 20:38
It is indeed fixed.

Thank you.

**Comment by codeHusky** [comment] 2019-03-04 21:53
Fixed in v2.0.0PRE9H2

**Closed as completed by codeHusky** 2019-03-04 21:53 UTC
Labels: bug, investigating
