### ISSUE TITLE
Invalid reward for spin result

### ISSUE THREAD

**Issue by jon100456** [codeHusky/HuskyCrates-Sponge#10] opened 2017-01-19 00:04 UTC
Reproducible by closing the inventory view before spin completes.

**Comment by codeHusky** [comment] 2017-01-19 00:34
.. What? It's possible that you're just incredibly lucky.

**Comment by jon100456** [comment] 2017-01-19 00:37
me and my friends can do it without a problem

**Comment by codeHusky** [comment] 2017-01-19 00:39
Config?

**Comment by jon100456** [comment] 2017-01-19 00:54
`cachedCrates=[]
crates {
    commandcrate {
        items=[
            {
                # The amount of an item.
                amount=1
                # The chance, out of 100, that this item will be drawn.
                chance=50
                # A command to run on picking this item.
                command="give %p minecraft:diamond 10"
                # The id of the item we're using
                id="minecraft:diamond"
                # A name
                name="Diamond Box"
            },
            {
                amount=24
                # Chances are assumed for items that don't have it.
                id="minecraft:dirt"
                # Lore.
                lore="Literally dirt. :)"
                name=Dirt
            }
        ]
        # Make sure this looks good everywhere :)
        name="ยง3Command Crate"
        # Types will be added in the future, but keeping this as a Spinner will keep your config future proof.
        type=Spinner
    }
}`

**Comment by codeHusky** [comment] 2017-01-19 00:54
oh my god please use pastebin.com

**Comment by codeHusky** [comment] 2017-01-19 01:16
Does it even ever get dirt when you normally spin?

**Comment by jon100456** [comment] 2017-01-19 01:30
yea if im in the gui only but if im out of the gui it only gave me diamond

**Comment by codeHusky** [comment] 2017-01-19 02:48
Looking into this

**Comment by rareCandyPixelmon** [comment] 2017-01-19 22:55
Hi All! I just wanted to say that I am also having this issue using the example config provided in the readme. Any time the spinner lands on Dirt it announces dirt but gives the 10 diamond as reward. In my instance it doesn't seem to matter if the GUI is open or closed.

**Comment by codeHusky** [comment] 2017-01-19 23:34
It has to do with how the logic system works. Adding one more item fixes it as far as ive found, but I'll try to fix it by changing the system

**Comment by codeHusky** [comment] 2017-01-21 04:50
I've confirmed that this is, in fact, the logic system's fault and has nothing to do with closing the window. I'm working on fixing it.
![image](https://cloud.githubusercontent.com/assets/6946558/22172029/cc7e5148-df62-11e6-8424-054ed275cd9b.png)

**Comment by codeHusky** [comment] 2017-01-21 04:55
With the default config from the README, I was able to get everything working just fine. I fixed a logic bug that made items run with the last command that the chest "saw", so that'll fix some things.

I'm unable to reproduce an invalid reward, but the command mixup is fixed now.

**Closed by codeHusky** 2017-01-21 04:55 UTC
